
path = "c:\program files\microsoft visual studio\2022\community\vc\tools\msvc\14.38.33130\bin\hostx64\x64"

cc = $(path)/cl.exe
link = $(path)/link.exe

exe = $(bin)/$(output).exe
pdb = $(bin)/$(output).pdb

win: $(exe)

$(bin)/%.o: $(src)/%.c
	$(cc) -Zi -c $^ -Fo:$@ -Fd:$(pdb)

$(exe): $(objects)
	$(link) -DEBUG $(objects) -PDB:$(pdb) $^ -OUT:$@

clean:
	rm -f $(bin)/*.o
	rm -f $(bin)/$(output)
