cc = gcc

cflags = -Wall -Werror

debug: cflags += -g

default:
	$(error target not specified)

debug: $(bin)/$(output)

release: $(bin)/$(output)

$(bin)/$(output): $(objects)
	$(cc) $(objects) -lSDL2 -o $@

ifneq (,$(filter debug release, $(MAKECMDGOALS)))
-include $(objects:.o=.d)
endif

$(bin)/%.d:
	$(cc) -I $(src) -MM -MT "$(bin)/$*.o $(bin)/$*.d" $(src)/$*.c -MF $@

$(bin)/%.o:
	$(cc) $(cflags) -c $(src)/$*.c -o $@

clean:
	rm -f $(bin)/*.d
	rm -f $(bin)/*.o
	rm -f $(bin)/$(output)
